repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3.13
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        language_version: python3.13
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.8.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.14.0
    hooks:
      - id: eslint
        name: eslint (javascript)
        files: ^frontend/.*\.(js|jsx|ts|tsx)$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets-hook
        args: [--baseline, .secrets.baseline]
